mainititearai/NaganoCake

app/controllers/members_controller.rb
app/views/members/sessions/bag.rails
app/views/members/show.html.erb

4/16時点でのすべてのプルリクエストです。
4/17日の初動でプルお願いします。

[Add]マイページの雛形の完成

---

app/controllers/members_controller.rb
app/views/members/edit.html.erb
app/views/members/show.html.erb

[Add]ユーザー編集機能と編集ページの作成

---

Gemfile

bootstrap update

---

app/controllers/members_controller.rb
app/models/member.rb
app/views/members/cancel.html.erb
app/views/members/edit.html.erb
app/views/members/show.html.erb

[Add]論理削除による退会機能、退会確認ページの追加

---

app/views/admin/home/top.html.erb
app/views/home/top.html.erb
app/views/layouts/_admins_footer.html.erb
app/views/layouts/_members_footer.html.erb
app/views/layouts/_members_header.html.erb

footer機能を追加しました。
adminには<%= render 'layouts/admins_footer' %>
memberには<%= render 'layouts/members_footer' %>を追加してください

[add]footer

---

app/views/admin/products/index.html.erb

admin側の商品一覧ページに新規登録ページへのリンクを追加しました

add new product link

---

app/views/members/registrations/new.html.erb

[Fix]membersの新規登録画面のformを修正しました

---

app/views/admin/products/edit.html.erb
app/views/admin/products/new.html.erb
app/views/admin/products/show.html.erb

adminのリンクを修正しました

---

app/controllers/admin/members_controller.rb
app/views/admin/members/index.html.erb

[Add]admin側の会員一覧ページの作成

---

app/controllers/cart_items_controller.rb
app/views/cart_items/index.html.erb
config/routes.rb

[fix]routes_destroyall

---

app/models/product.rb
app/views/admin/products/show.html.erb

商品登録のエラーを修正しました

---

Gemfile
Gemfile.lock
app/controllers/admin/members_controller.rb
app/views/admin/members/edit.html.erb
app/views/admin/members/index.html.erb
app/views/admin/members/show.html.erb
config/application.rb
config/locales/ja.yml

コンフィグファイルとか結構触ってるので、早めにプルお願いします！

enum日本語化,adminページとmember操作全て完成

---

config/routes.rb

[Fix]routesの記述ミスを変更しています

---

app/controllers/cart_items_controller.rb
app/views/cart_items/index.html.erb

[update]cart_item

---

app/controllers/orders_controller.rb
app/controllers/shipping_addresses_controller.rb
db/migrate/20200418094805_remove_postage_from_orders.rb
db/schema.rb

[Add]配送先一覧ページと、編集、削除機能を追加しました

---

app/controllers/cart_items_controller.rb

[fix]cart_item

---

app/controllers/orders_controller.rb
app/models/order.rb
app/views/orders/confirm.html.erb
app/views/orders/new.html.erb
config/locales/ja.yml

注文機能を追加しました

---

app/controllers/shipping_addresses_controller.rb
app/models/shipping_address.rb
app/views/orders/new.html.erb

[Add]注文情報入力ページのプルダウンの表記変更

---

app/controllers/orders_controller.rb
app/views/orders/index.html.erb

注文ページの配送先新規登録に対応しました

---

app/controllers/orders_controller.rb
app/views/orders/index.html.erb
config/routes.rb

ルーティングを変更しました

---

app/views/layouts/_admins_header.html.erb
app/views/orders/thanks.html.erb

[update]thanks

---

app/controllers/orders_controller.rb
app/views/orders/index.html.erb
app/views/orders/show.html.erb

注文履歴一覧と詳細ページを追加しました(member)

---

app/controllers/orders_controller.rb
app/views/admin/home/top.html.erb
app/views/layouts/_members_footer.html.erb
app/views/orders/confirm.html.erb

[update]cart_item_view

---

app/assets/stylesheets/admin/orders.scss
app/assets/stylesheets/application.scss
app/controllers/admin/orders_controller.rb
app/models/order_item.rb
app/views/admin/orders/index.html.erb
app/views/admin/orders/show.html.erb
config/locales/ja.yml

注文履歴詳細画面に製作ステータスの変更機能を追加

---

app/controllers/orders_controller.rb
app/views/admin/products/index.html.erb
app/views/orders/index.html.erb
app/views/orders/show.html.erb

member側の注文一覧詳細画面の修正

---

app/controllers/products_controller.rb
app/views/admin/products/edit.html.erb
app/views/admin/products/index.html.erb
app/views/admin/products/new.html.erb
app/views/admin/products/show.html.erb
app/views/products/index.html.erb
app/views/products/show.html.erb

商品ページを変更しました

---

Gemfile
Gemfile.lock
app/assets/stylesheets/application.scss
app/views/layouts/_members_footer.html.erb
app/views/layouts/_members_header.html.erb
app/views/layouts/application.html.erb

フッター完成しました

---

app/controllers/orders_controller.rb
app/views/orders/confirm.html.erb

注文に関するエラーを修正しました

---

app/controllers/admin/genres_controller.rb
app/controllers/admin/orders_controller.rb
app/controllers/application_controller.rb
app/controllers/orders_controller.rb
app/controllers/shipping_addresses_controller.rb
app/views/admin/members/show.html.erb
app/views/cart_items/index.html.erb
app/views/orders/index.html.erb
app/views/orders/show.html.erb
config/initializers/time_formats.rb
config/locales/ja.yml

テストを見ながら、細かい箇所を数点修正しました

---

app/controllers/orders_controller.rb

修正点が消えていたので再プッシュしました

---

app/controllers/cart_items_controller.rb
app/controllers/products_controller.rb
app/views/home/top.html.erb
app/views/products/index.html.erb

カート内商品が0になったときにその商品をカートから削除
トップページの画像をクリックできるようになりました
商品一覧ページの不具合を修正

カート、商品のビュー修正

---

app/views/shipping_addresses/edit.html.erb
app/views/shipping_addresses/index.html.erb

配送先編集ページを編集しました

---

app/views/orders/confirm.html.erb
app/views/orders/new.html.erb

注文情報入力、確認画面のViewを編集しました

---

app/controllers/orders_controller.rb
app/views/layouts/_admins_header.html.erb
app/views/orders/index.html.erb
app/views/orders/show.html.erb
app/views/products/index.html.erb

メンバーサイトへのリンク

---

config/routes.rb

routes忘れてました

---

app/assets/stylesheets/application.scss
app/views/cart_items/index.html.erb
app/views/home/about.html.erb
app/views/home/top.html.erb
app/views/members/show.html.erb
app/views/orders/confirm.html.erb
app/views/orders/index.html.erb
app/views/orders/new.html.erb
app/views/orders/show.html.erb
app/views/products/index.html.erb
app/views/shipping_addresses/index.html.erb

タイトルの字体を変更しました

---

app/views/admin/home/top.html.erb
app/views/admins/sessions/new.html.erb
app/views/layouts/_admins_header.html.erb

管理者側のヘッダーを調整しました

---

app/assets/javascripts/searches.coffee
app/assets/stylesheets/searches.scss
app/controllers/searches_controller.rb
app/helpers/searches_helper.rb
app/models/product.rb
app/views/layouts/_members_header.html.erb
app/views/searches/index.html.erb
config/routes.rb
test/controllers/searches_controller_test.rb

[update]search

---

app/assets/javascripts/admin/member_searches.coffee
app/assets/stylesheets/admin/member_searches.scss
app/controllers/admin/member_searches_controller.rb
app/helpers/admin/member_searches_helper.rb
app/models/member.rb
app/views/admin/member_searches/index.html.erb
app/views/layouts/_members_header.html.erb
config/routes.rb
test/controllers/admin/member_searches_controller_test.rb

[update]search_member

---

.gitignore
Gemfile
app/assets/javascripts/application.js
app/assets/stylesheets/application.scss
app/controllers/orders_controller.rb
app/views/orders/confirm.html.erb
app/views/orders/create.html.erb
app/views/orders/new.html.erb
app/views/orders/show.html.erb

支払い機能を追加しました

---

app/controllers/application_controller.rb
app/controllers/members/confirmations_controller.rb
app/views/members/mailer/confirmation_instructions.html.erb

[fix]メールアドレス認証メールを新規登録時とプロフィール変更時で内容の変更

---

app/controllers/home_controller.rb
app/views/home/change_password.html.erb
config/routes.rb

[add]change_password

---

app/controllers/admin/genres_controller.rb
app/views/admin/genres/edit.html.erb
app/views/admin/genres/index.html.erb
app/views/admin/products/edit.html.erb
app/views/admin/products/index.html.erb
app/views/admin/products/new.html.erb
app/views/admin/products/show.html.erb

バリデーションメッセージ

---

app/helpers/application_helper.rb
app/views/admin/products/index.html.erb
app/views/products/index.html.erb
app/views/products/show.html.erb

[add]price
